import React, { createContext, useState, useContext, useCallback, useMemo, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Get stored language from localStorage or default to English
    const initialLanguage = localStorage.getItem('selectedLanguage') || 'en';
    const [currentLanguage, setCurrentLanguage] = useState(initialLanguage);
    
    // All available languages - only English and Vietnamese
    const languages = useMemo(() => [
        { code: 'en', name: 'English' },
        { code: 'vi', name: 'Vietnamese' }
    ], []);

    // Static translations for common UI elements
    const staticTranslations = useMemo(() => ({
        en: {
            'Flashcards': 'Flashcards',
            'Readings': 'Readings',
            'Writing': 'Writing',
            'Discover': 'Discover',
            'Sign In': 'Sign In',
            'Get Started': 'Get Started',
            'Select Language': 'Select Language',
            'Home': 'Home',
            'Your Flashcards': 'Your Flashcards',
            'Explore Flashcards': 'Explore Flashcards',
            'Your Readings': 'Your Readings',
            'Explore Tests': 'Explore Tests',
            'Your Writing': 'Your Writing',
            'Explore Writing': 'Explore Writing',
            'Writing Exercises': 'Writing Exercises',
            'Progress': 'Progress',
            'Logout': 'Logout',
            'Explore': 'Explore',
            'Multiple Choice Tests': 'Multiple Choice Tests',
            'Enter API Key': 'Enter API Key',
            'Learning Language': 'Learning Language',
            'Native Language': 'Native Language',
            'My Flashcards': 'My Flashcards',
            'Create Manual Set': 'Create Manual Set',
            'Create AI Set': 'Create AI Set',
            'Study Without an Account': 'Study Without an Account',
            'All flashcard sets shown here are public and can be studied without signing in, but your learning time, progress and streaks will not be saved.': 'All flashcard sets shown here are public and can be studied without signing in, but your learning time, progress and streaks will not be saved.',
            'Loading...': 'Loading...',
            'Cards': 'Cards',
            'Level': 'Level',
            'Learners': 'Learners',
            'Items Per Page': 'Items Per Page',
            'You haven\'t created any flashcard sets yet.': 'You haven\'t created any flashcard sets yet.',
            'Create New': 'Create New',
            'Edit': 'Edit',
            'Delete': 'Delete',
            'Study': 'Study',
            'Save': 'Save',
            'Cancel': 'Cancel',
            'Confirm': 'Confirm',
            'Search': 'Search',
            'No results found': 'No results found',
            'View': 'View',
            'Back': 'Back',
            'Next': 'Next',
            'Previous': 'Previous',
            'Submit': 'Submit',
            'Settings': 'Settings',
            'Profile': 'Profile',
            'Account': 'Account',
            'Help': 'Help',
            'Contact': 'Contact',
            'About': 'About',
            'Terms': 'Terms',
            'Privacy': 'Privacy',
            'Copyright': 'Copyright',
            'All rights reserved': 'All rights reserved',
            'Master Languages with': 'Master Languages with',
            'Smart Flashcards': 'Smart Flashcards',
            'Transform your language learning journey with AI-powered flashcards, personalized study plans, and interactive exercises. Start learning smarter, not harder.': 'Transform your language learning journey with AI-powered flashcards, personalized study plans, and interactive exercises. Start learning smarter, not harder.',
            'Start Free Trial': 'Start Free Trial',
            'Explore Features': 'Explore Features',
            'All Languages': 'All Languages',
            'English': 'English',
            'Vietnamese': 'Vietnamese',
            'Spanish': 'Spanish',
            'French': 'French',
            'German': 'German',
            'Japanese': 'Japanese',
            'Korean': 'Korean',
            'Chinese': 'Chinese',
            'Title is required': 'Title is required',
            'Description': 'Description',
            'Example': 'Example',
            'Word/Phrase': 'Word/Phrase',
            'Translation': 'Translation',
            'Add Card': 'Add Card',
            'Edit Card': 'Edit Card',
            'Delete Card': 'Delete Card',
            'Edit Set': 'Edit Set',
            'Delete Set': 'Delete Set',
            'Change Visibility': 'Change Visibility',
            'Generate with AI': 'Generate with AI',
            'Import Cards': 'Import Cards',
            'Share': 'Share',
            'Copy Link': 'Copy Link',
            'Link Copied!': 'Link Copied!',
            'Public': 'Public',
            'Private': 'Private',
            'Created': 'Created',
            'Updated': 'Updated',
            'Learning Progress': 'Learning Progress',
            'Current Streak': 'Current Streak',
            'Longest Streak': 'Longest Streak',
            'Total Learning Time': 'Total Learning Time',
            'Recent Session': 'Recent Session',
            'Learning Calendar': 'Learning Calendar',
            'Start Learning': 'Start Learning',
            'Study Now': 'Study Now',
            'days': 'days',
            'minutes': 'minutes',
            'hours': 'hours',
            'No data found': 'No data found',
            'You have no learning data yet. Start learning to track your progress!': 'You have no learning data yet. Start learning to track your progress!',
            'Your Achievements': 'Your Achievements',
            // Additional translations for flashcards
            'Fullscreen Study': 'Fullscreen Study',
            'End Session': 'End Session',
            'I don\'t know': 'I don\'t know',
            'I know this': 'I know this',
            'Mode': 'Mode',
            'Sequential': 'Sequential',
            'Shuffle': 'Shuffle',
            'Difficulty': 'Difficulty',
            'Title': 'Title',
            'Language': 'Language',
            'Front': 'Front',
            'Back': 'Back',
            'Term': 'Term',
            'Definition': 'Definition',
            'Read more': 'Read more',
            // Additional translations for writing
            'Generate AI Topic': 'Generate AI Topic',
            'Title for your exercise': 'Title for your exercise',
            'Generate Topic': 'Generate Topic',
            'Create Writing Exercise': 'Create Writing Exercise',
            'Write your prompt here': 'Write your prompt here',
            'Please select a different learning and native language': 'Please select a different learning and native language',
            'Please wait...': 'Please wait...',
            // Additional translations for progress
            'Learning Stats': 'Learning Stats',
            'Streak': 'Streak',
            'Your Learning Progress': 'Your Learning Progress',
            'Track your development': 'Track your development',
            'Loading data...': 'Loading data...',
            'New Reading': 'New Reading',
            'Study Flashcards': 'Study Flashcards',
            'New Writing': 'New Writing',
            'Read New': 'Read New',
            'Start learning now': 'Start learning now',
            // Additional translations for reading
            'Reading Exercises': 'Reading Exercises',
            'Multiple Choice': 'Multiple Choice',
            'Create AI Test': 'Create AI Test',
            'Create Test': 'Create Test',
            'Begin Test': 'Begin Test',
            // Additional for progress page
            'Keep your motivation every day!': 'Keep your motivation every day!',
            'Your record so far!': 'Your record so far!',
            'Time invested in your learning': 'Time invested in your learning',
            'Continue maintaining your learning habits!': 'Continue maintaining your learning habits!',
            'Note: Calendar only shows your most recent continuous learning streak.': 'Note: Calendar only shows your most recent continuous learning streak.',
            '3-Day Streak': '3-Day Streak',
            'Study every day for 3 consecutive days': 'Study every day for 3 consecutive days',
            '10 Minutes of Learning': '10 Minutes of Learning', 
            'Study for a total of 10 minutes': 'Study for a total of 10 minutes',
            '7-Day Streak': '7-Day Streak',
            'Study every day for 7 consecutive days': 'Study every day for 7 consecutive days',
            'Back to Set': 'Back to Set',
            'Click to reveal definition': 'Click to reveal definition',
            'Click to flip back': 'Click to flip back',
            'cards': 'cards',
            'Study Time': 'Study Time',
            'Known Cards': 'Known Cards',
            'Cards Viewed': 'Cards Viewed',
            'Accuracy': 'Accuracy',
            // Reading test UI elements
            'Generate Tests with AI': 'Generate Tests with AI',
            'Enter a topic (optional) or leave blank for AI to choose one.': 'Enter a topic (optional) or leave blank for AI to choose one.',
            'Select options below to customize your reading test.': 'Select options below to customize your reading test.',
            'AI will automatically generate a reading passage and multiple-choice questions.': 'AI will automatically generate a reading passage and multiple-choice questions.',
            'Example topics:': 'Example topics:',
            'Filter by Language:': 'Filter by Language:',
            'My Reading Tests': 'My Reading Tests',
            'My Multiple Choice Tests': 'My Multiple Choice Tests',
            'Create New Test': 'Create New Test',
            'All languages': 'All languages',
            'Difficulty Level:': 'Difficulty Level:',
            'Level 3 - Intermediate': 'Level 3 - Intermediate',
            'AI test generation requires a Google Gemini API key.': 'AI test generation requires a Google Gemini API key.',
            'If you don\'t have one yet, the system will guide you to add it.': 'If you don\'t have one yet, the system will guide you to add it.',
            'Create AI Reading Test': 'Create AI Reading Test',
            // Level labels
            'Level 1 - Beginner': 'Level 1 - Beginner',
            'Level 2 - Elementary': 'Level 2 - Elementary',
            'Level 3 - Intermediate': 'Level 3 - Intermediate',
            'Level 3 - Pre-Intermediate': 'Level 3 - Pre-Intermediate',
            'Level 4 - Intermediate': 'Level 4 - Intermediate',
            'Level 4 - Upper Intermediate': 'Level 4 - Upper Intermediate',
            'Level 5 - Advanced': 'Level 5 - Advanced',
            'Level 5 - Upper Intermediate': 'Level 5 - Upper Intermediate',
            'Level 6 - Advanced': 'Level 6 - Advanced',
            'Level 6 - Proficient': 'Level 6 - Proficient',
            'Tạo bài kiểm tra bằng AI': 'Tạo bài kiểm tra bằng AI', 
            'Enter a topic (optional) or leave blank for AI to choose one. Select options below to customize your reading test.': 'Nhập một chủ đề (tùy chọn) hoặc để trống để AI chọn một chủ đề. Chọn các tùy chọn bên dưới để tùy chỉnh bài kiểm tra đọc của bạn.',
            'AI will automatically generate a reading passage and multiple-choice questions. Example topics: "Climate Change", "Space Exploration", "Vietnamese Culture"...': 'AI sẽ tự động tạo một đoạn văn đọc và các câu hỏi trắc nghiệm. Ví dụ các chủ đề: "Biến đổi Khí hậu", "Khám phá Không gian", "Văn hóa Việt Nam"...'
        },
        vi: {
            'Flashcards': 'Thẻ ghi nhớ',
            'Readings': 'Bài đọc',
            'Writing': 'Viết',
            'Discover': 'Khám phá',
            'Sign In': 'Đăng nhập',
            'Get Started': 'Bắt đầu ngay',
            'Select Language': 'Chọn ngôn ngữ',
            'Home': 'Trang chủ',
            'Your Flashcards': 'Thẻ ghi nhớ của bạn',
            'Explore Flashcards': 'Khám phá thẻ ghi nhớ',
            'Your Readings': 'Bài đọc của bạn',
            'Explore Tests': 'Khám phá bài kiểm tra',
            'Your Writing': 'Bài viết của bạn',
            'Explore Writing': 'Khám phá bài viết',
            'Writing Exercises': 'Bài tập viết',
            'Progress': 'Tiến độ',
            'Logout': 'Đăng xuất',
            'Explore': 'Khám phá',
            'Multiple Choice Tests': 'Bài kiểm tra trắc nghiệm',
            'Enter API Key': 'Nhập khóa API',
            'Learning Language': 'Ngôn ngữ học',
            'Native Language': 'Ngôn ngữ bản địa',
            'My Flashcards': 'Thẻ ghi nhớ của tôi',
            'Create Manual Set': 'Tạo bộ thẻ thủ công',
            'Create AI Set': 'Tạo bộ thẻ bằng AI',
            'Study Without an Account': 'Học mà không cần tài khoản',
            'All flashcard sets shown here are public and can be studied without signing in, but your learning time, progress and streaks will not be saved.': 'Tất cả các bộ thẻ ghi nhớ hiển thị ở đây là công khai và có thể được học mà không cần đăng nhập, nhưng thời gian học, tiến độ và chuỗi ngày học của bạn sẽ không được lưu lại.',
            'Loading...': 'Đang tải...',
            'Cards': 'Thẻ',
            'Level': 'Cấp độ',
            'Learners': 'Người học',
            'Items Per Page': 'Số mục trên mỗi trang',
            'You haven\'t created any flashcard sets yet.': 'Bạn chưa tạo bộ thẻ ghi nhớ nào.',
            'Create New': 'Tạo mới',
            'Edit': 'Chỉnh sửa',
            'Delete': 'Xóa',
            'Study': 'Học',
            'Save': 'Lưu',
            'Cancel': 'Hủy',
            'Confirm': 'Xác nhận',
            'Search': 'Tìm kiếm',
            'No results found': 'Không tìm thấy kết quả',
            'View': 'Xem',
            'Back': 'Quay lại',
            'Next': 'Tiếp theo',
            'Previous': 'Trước',
            'Submit': 'Gửi',
            'Settings': 'Cài đặt',
            'Profile': 'Hồ sơ',
            'Account': 'Tài khoản',
            'Help': 'Trợ giúp',
            'Contact': 'Liên hệ',
            'About': 'Giới thiệu',
            'Terms': 'Điều khoản',
            'Privacy': 'Quyền riêng tư',
            'Copyright': 'Bản quyền',
            'All rights reserved': 'Tất cả các quyền được bảo lưu',
            'Master Languages with': 'Làm chủ ngôn ngữ với',
            'Smart Flashcards': 'Thẻ ghi nhớ thông minh',
            'Transform your language learning journey with AI-powered flashcards, personalized study plans, and interactive exercises. Start learning smarter, not harder.': 'Biến đổi hành trình học ngôn ngữ của bạn với thẻ ghi nhớ được hỗ trợ bởi AI, kế hoạch học tập cá nhân hóa và bài tập tương tác. Bắt đầu học thông minh hơn, không phải khó khăn hơn.',
            'Start Free Trial': 'Dùng thử miễn phí',
            'Explore Features': 'Khám phá tính năng',
            'All Languages': 'Tất cả ngôn ngữ',
            'English': 'Tiếng Anh',
            'Vietnamese': 'Tiếng Việt',
            'Spanish': 'Tiếng Tây Ban Nha',
            'French': 'Tiếng Pháp',
            'German': 'Tiếng Đức',
            'Japanese': 'Tiếng Nhật',
            'Korean': 'Tiếng Hàn',
            'Chinese': 'Tiếng Trung',
            'Title is required': 'Tiêu đề là bắt buộc',
            'Description': 'Mô tả',
            'Example': 'Ví dụ',
            'Word/Phrase': 'Từ/Cụm từ',
            'Translation': 'Bản dịch',
            'Add Card': 'Thêm thẻ',
            'Edit Card': 'Chỉnh sửa thẻ',
            'Delete Card': 'Xóa thẻ',
            'Edit Set': 'Chỉnh sửa bộ',
            'Delete Set': 'Xóa bộ',
            'Change Visibility': 'Thay đổi chế độ hiển thị',
            'Generate with AI': 'Tạo bằng AI',
            'Import Cards': 'Nhập thẻ',
            'Share': 'Chia sẻ',
            'Copy Link': 'Sao chép liên kết',
            'Link Copied!': 'Đã sao chép liên kết!',
            'Public': 'Công khai',
            'Private': 'Riêng tư',
            'Created': 'Đã tạo',
            'Updated': 'Đã cập nhật',
            'Learning Progress': 'Tiến độ học tập',
            'Current Streak': 'Chuỗi ngày hiện tại',
            'Longest Streak': 'Chuỗi ngày dài nhất',
            'Total Learning Time': 'Tổng thời gian học',
            'Recent Session': 'Buổi học gần đây',
            'Learning Calendar': 'Lịch học tập',
            'Start Learning': 'Bắt đầu học',
            'Study Now': 'Học ngay',
            'Days': 'Ngày',
            'minutes': 'phút',
            'hours': 'giờ',
            'No data found': 'Không tìm thấy dữ liệu',
            'You have no learning data yet. Start learning to track your progress!': 'Bạn chưa có dữ liệu học tập. Hãy bắt đầu học để theo dõi tiến độ!',
            'Your Achievements': 'Thành tựu của bạn',
            // Additional translations for flashcards
            'Fullscreen Study': 'Học toàn màn hình',
            'End Session': 'Kết thúc phiên',
            'I don\'t know': 'Tôi không biết',
            'I know this': 'Tôi biết điều này',
            'Mode': 'Chế độ',
            'Sequential': 'Tuần tự',
            'Shuffle': 'Xáo trộn',
            'Difficulty': 'Độ khó',
            'Title': 'Tiêu đề',
            'Language': 'Ngôn ngữ',
            'Front': 'Mặt trước',
            'Back': 'Mặt sau',
            'Term': 'Thuật ngữ',
            'Definition': 'Định nghĩa',
            'Read more': 'Đọc thêm',
            // Additional translations for writing
            'Generate AI Topic': 'Tạo chủ đề AI',
            'Title for your exercise': 'Tiêu đề cho bài tập của bạn',
            'Generate Topic': 'Tạo chủ đề',
            'Create Writing Exercise': 'Tạo bài tập viết',
            'Write your prompt here': 'Viết hướng dẫn của bạn tại đây',
            'Please select a different learning and native language': 'Vui lòng chọn ngôn ngữ học và ngôn ngữ bản địa khác nhau',
            'Please wait...': 'Vui lòng đợi...',
            // Additional translations for progress
            'Learning Stats': 'Thống kê học tập',
            'Streak': 'Chuỗi ngày',
            'Your Learning Progress': 'Tiến độ học tập của bạn',
            'Track your development': 'Theo dõi sự phát triển của bạn',
            'Loading data...': 'Đang tải dữ liệu...',
            'New Reading': 'Đọc bài mới',
            'Study Flashcards': 'Học thẻ ghi nhớ',
            'New Writing': 'Viết bài mới',
            'Read New': 'Đọc mới',
            'Start learning now': 'Bắt đầu học ngay',
            // Additional translations for reading
            'Reading Exercises': 'Bài tập đọc',
            'Multiple Choice': 'Trắc nghiệm',
            'Create AI Test': 'Tạo bài kiểm tra AI',
            'Create Test': 'Tạo bài kiểm tra',
            'Begin Test': 'Bắt đầu kiểm tra',
            // Additional for progress page
            'Keep your motivation every day!': 'Giữ vững động lực mỗi ngày!',
            'Your record so far!': 'Kỷ lục của bạn cho đến nay!',
            'Time invested in your learning': 'Thời gian đầu tư cho việc học của bạn',
            'Continue maintaining your learning habits!': 'Tiếp tục duy trì thói quen học tập!',
            'Note: Calendar only shows your most recent continuous learning streak.': 'Lưu ý: Lịch chỉ hiển thị chuỗi ngày học liên tục gần nhất.',
            '3-Day Streak': 'Học Liên Tục 3 Ngày',
            'Study every day for 3 consecutive days': 'Học mỗi ngày trong 3 ngày liên tiếp',
            '10 Minutes of Learning': '10 Phút Học Tập', 
            'Study for a total of 10 minutes': 'Học tổng cộng 10 phút',
            '7-Day Streak': 'Học Liên Tục 7 Ngày',
            'Study every day for 7 consecutive days': 'Học mỗi ngày trong 7 ngày liên tiếp',
            'Back to Set': 'Quay lại bộ thẻ',
            'Click to reveal definition': 'Nhấp để hiện định nghĩa',
            'Click to flip back': 'Nhấp để lật lại',
            'cards': 'thẻ',
            'Study Time': 'Thời gian học',
            'Known Cards': 'Thẻ đã biết',
            'Cards Viewed': 'Thẻ đã xem',
            'Accuracy': 'Độ chính xác',
            // Reading test UI elements
            'Generate Tests with AI': 'Tạo bài kiểm tra bằng AI',
            'Enter a topic (optional) or leave blank for AI to choose one.': 'Nhập một chủ đề (tùy chọn) hoặc để trống để AI chọn một chủ đề.',
            'Select options below to customize your reading test.': 'Chọn các tùy chọn bên dưới để tùy chỉnh bài kiểm tra đọc của bạn.',
            'AI will automatically generate a reading passage and multiple-choice questions.': 'AI sẽ tự động tạo một đoạn văn đọc và các câu hỏi trắc nghiệm.',
            'Example topics:': 'Ví dụ các chủ đề:',
            'Filter by Language:': 'Lọc theo ngôn ngữ:',
            'My Reading Tests': 'Bài kiểm tra đọc của tôi',
            'My Multiple Choice Tests': 'Bài kiểm tra trắc nghiệm của tôi',
            'Create New Test': 'Tạo bài kiểm tra mới',
            'All languages': 'Tất cả ngôn ngữ',
            'Difficulty Level:': 'Cấp độ khó:',
            'Level 3 - Intermediate': 'Cấp độ 3 - Trung cấp',
            'AI test generation requires a Google Gemini API key.': 'Tạo bài kiểm tra bằng AI yêu cầu một khóa API Google Gemini.',
            'If you don\'t have one yet, the system will guide you to add it.': 'Nếu bạn chưa có, hệ thống sẽ hướng dẫn bạn thêm vào.',
            'Tạo bài kiểm tra bằng AI': 'Tạo bài kiểm tra bằng AI',
            // Level labels
            'Level 1 - Beginner': 'Cấp độ 1 - Sơ cấp',
            'Level 2 - Elementary': 'Cấp độ 2 - Căn bản',
            'Level 3 - Intermediate': 'Cấp độ 3 - Trung cấp',
            'Level 3 - Pre-Intermediate': 'Cấp độ 3 - Tiền trung cấp',
            'Level 4 - Intermediate': 'Cấp độ 4 - Trung cấp',
            'Level 4 - Upper Intermediate': 'Cấp độ 4 - Trung cấp cao',
            'Level 5 - Advanced': 'Cấp độ 5 - Cao cấp',
            'Level 5 - Upper Intermediate': 'Cấp độ 5 - Trung cấp cao',
            'Level 6 - Advanced': 'Cấp độ 6 - Cao cấp',
            'Level 6 - Proficient': 'Cấp độ 6 - Thành thạo',
            'Tạo bài kiểm tra bằng AI': 'Tạo bài kiểm tra bằng AI', 
            'Enter a topic (optional) or leave blank for AI to choose one. Select options below to customize your reading test.': 'Nhập một chủ đề (tùy chọn) hoặc để trống để AI chọn một chủ đề. Chọn các tùy chọn bên dưới để tùy chỉnh bài kiểm tra đọc của bạn.',
            'AI will automatically generate a reading passage and multiple-choice questions. Example topics: "Climate Change", "Space Exploration", "Vietnamese Culture"...': 'AI sẽ tự động tạo một đoạn văn đọc và các câu hỏi trắc nghiệm. Ví dụ các chủ đề: "Biến đổi Khí hậu", "Khám phá Không gian", "Văn hóa Việt Nam"...',
            //Adding 
            'Questions': 'Số câu hỏi',
            'Learners': 'Số người học',
            'Explore Multiple Choice Tests': 'Khám phá bài trắc nghiệm đọc hiểu',
            'All multiple choice tests shown here are public and can be taken without signing in, but your scores and progress will not be saved.': 'Tất cả các bộ bài trắc nghiệm hiển thị ở đây là công khai và có thể được học mà không cần đăng nhập, nhưng thời gian học, tiến độ và chuỗi ngày học của bạn sẽ không được lưu lại.',
            'Take Test': 'Học ngay',
            'Explore Writing Exercises': 'Khám phá bài viết',
            'All writing exercises shown here are public and can be practiced without signing in, but your progress will not be saved.': 'Tất cả các bộ bài viết hiển thị ở đây là công khai và có thể được học mà không cần đăng nhập, nhưng thời gian học, tiến độ và chuỗi ngày học của bạn sẽ không được lưu lại.',
            'Active Users': 'Người dùng hoạt động',
            'Flashcards Created': 'Thẻ ghi nhớ được tạo',
            'Success Rate': 'Tỷ lệ thành công',
            'Popular Flashcard Sets': 'Các Bộ Thẻ Ghi Nhớ Phổ Biến',
            'Explore All': 'Khám phá ngay',
            'Sign Up to Study': 'Đăng ký học ngay!',
            'Featured': 'Nổi Bật',
            'Start your language journey today!': 'Quẩy banh nóc ngoại ngữ ngay và luôn!',
            'Join thousands of successful language learners. Create your account to access personalized learning features.': 'Tham gia cùng hàng ngàn “chiến thần ngoại ngữ”! Tạo tài khoản để khám phá trải nghiệm học cá nhân hóa siêu mượt!',
            'AI-Powered Learning': 'Học với AI – Cứ để máy lo!',
            'Personalized to match your learning style': 'Phù hợp với phong cách học của chính bạn – không đụng hàng ai luôn!',
            'Smart Flashcards': 'Flashcard "xịn" có chọn lọc',
            'Enhanced with spaced repetition technology': 'Lặp đi lặp lại đúng lúc, nhớ hoài không quên – học là dính!',
            'Track Your Progress': 'Theo dõi tiến độ – Nhìn là muốn học tiếp!',
            'Visual statistics to keep you motivated': 'Biểu đồ đẹp như crush, xem là có động lực liền!',
            'Create Your Account': 'Lập "nick" xịn, chiến thôi!',
            'It\'s quick and easy!': 'Vài nốt nhạc là xong!',
            'Continue': 'Tiếp tục nà',
            'Already have an account?': 'Chiễn sĩ có tài khoản rồi hả? Đăng nhập chiến thôi 👉' ,
            'Create Account': 'Chiến thôiiii',
            'Welcome back to your language journey!': 'Mừng bạn quay lại "đường đua" ngoại ngữ!',
            'Log in to continue your progress, practice vocabulary, and achieve your language goals.': 'Đăng nhập để tiếp tục tiến độ, luyện từ vựng và đạt mục tiêu ngôn ngữ của bạn.',
            'Keep your learning momentum going': 'Giữ "lửa" học tập mỗi ngày.',
            'Track your progress and earn rewards': 'Theo dõi tiến độ và nhận thưởng.',
            'Continue right where you left off': 'Tiếp tục ngay chỗ bạn dừng lại.',
            'Today': 'Hôm nay',
            'Explore Public Flashcards': 'Khám phá Thẻ Ghi Nhớ Công Khai',
            'Discover flashcard sets created by other users to expand your vocabulary.': 'Khám phá các bộ thẻ ghi nhớ do người dùng khác tạo để mở rộng vốn từ vựng của bạn.',
            'Browse Public Flashcards': 'Khám phá ngay!',
            'Create AI Reading Test':'Tạo bài kiểm tra bằng AI',
            'Enter a topic (optional) or leave blank for AI to choose one. Select options below to customize your reading test. AI will automatically generate a reading passage and multiple-choice questions. Example topics: "Climate Change", "Space Exploration", "Vietnamese Culture"...': 'Nhập chủ đề (tùy chọn) hoặc bỏ trống để AI tự chọn "món". Tùy chỉnh bài đọc hiểu bên dưới theo ý bạn. AI sẽ tự tạo đoạn văn và câu hỏi trắc nghiệm. Ví dụ chủ đề: "Biến đổi khí hậu", "Khám phá vũ trụ", "Văn hóa Việt Nam"... ',
            'Improve your writing skills through specially designed writing exercises.': 'Nâng cao kỹ năng viết của bạn qua các bài tập được thiết kế đặc biệt. ',
            'Generate Writing Topic with AI':'Tạo Chủ Đề Viết bằng AI ',
            'How it works': 'Cách hoạt động',
            'AI will automatically generate a writing topic based on your learning language and native language. This feature requires that you have saved your Gemini API key.': 'AI sẽ tự động tạo chủ đề viết dựa trên ngôn ngữ học và ngôn ngữ mẹ đẻ của bạn. Tính năng này yêu cầu bạn đã lưu khóa API Gemini.',
            'Topic Title': 'Tên Topic',
            'Enter a title for your writing topic': 'Nhập tiêu đề cho chủ đề viết của bạn',
            'Learning Language': 'Ngôn ngữ học',
            'Native Language': 'Tiếng "mẹ đẻ"',
            'Generate Topic': 'Tạo Chủ Đề',
            'Minutes': 'Phút',
            'minutes': 'phút',
            'Hours': 'Giờ'
        }
    }), []);

    // Simple translation function - returns static translation if available
    const translateText = useCallback((text) => {
        if (!text) return '';
        
        // If not English and we have a translation, use it
        if (currentLanguage !== 'en' && 
            staticTranslations[currentLanguage] && 
            staticTranslations[currentLanguage][text]) {
            return staticTranslations[currentLanguage][text];
        }
        
        // Otherwise return original text
        return text;
    }, [currentLanguage, staticTranslations]);

    // Change language and save to localStorage
    const changeLanguage = useCallback((langCode) => {
        if (langCode && languages.some(lang => lang.code === langCode)) {
            setCurrentLanguage(langCode);
            localStorage.setItem('selectedLanguage', langCode);
        }
    }, [languages]);

    // Memoize context value to prevent unnecessary re-renders
    const contextValue = useMemo(() => ({
        currentLanguage,
        languages,
        translateText,
        changeLanguage
    }), [currentLanguage, languages, translateText, changeLanguage]);

    return (
        <LanguageContext.Provider value={contextValue}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default LanguageContext; 